version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    env_file:
      - ./env/kafka.env
    volumes:
      - ./kafka/server.properties:/etc/kafka/server.properties
    command: ["sh", "-c", "kafka-server-start /etc/kafka/server.properties"]

  redis:
    image: redis:7.0.11
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    env_file:
      - ./env/redis.env

  postgres:
    image: postgres:15.3
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./env/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh:ro
      
volumes:
  postgres-data:

# mailhog:
  #   image: mailhog/mailhog
  #   container_name: mailhog
  #   ports:
  #     - "8025:8025"  # Web UI
  #     - "1025:1025"  # SMTP port
 
#  For user service:
  # user-service:
  #   build:
  #     context: ../user-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     SPRING_PROFILES_ACTIVE: docker
  #   depends_on:
  #     - kafka
  #     - redis
  #     - postgres
