services:
  user-service:
    build:
      context: ../user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka
      - redis
      - postgres